apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: ${{ values.repoUrl | replace("github.com?owner=", "") | replace("&repo=","/") | dump }}
    backstage.io/kubernetes-label-selector: 'app=${{ values.name }}'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: ${{ values.owner | dump }}
  lifecycle: experimental
  dependsOn: 
  - ${{ values.dependency | dump }}
  - "resource:default/${{ values.db }}"

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.db | dump }}
spec:
  type: database
  owner: ${{ values.owner | dump }}