version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    # network_mode: "host"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superman
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    # network_mode: "host"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  lighthouse:
    image: spotify/lighthouse-audit-service:latest
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: superman
      LAS_PORT: 4008
      LAS_CORS: true
    ports:
      - "4008:4008"
      
volumes:
  db:
    driver: local

