---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Merchants
spec:
  owner: dev
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Customer
spec:
  owner: lead
# ---
# # https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: example-website
#   annotations:
#     lighthouse.com/website-url: https://www.keyvalue.systems
# spec:
#   type: website
#   lifecycle: production
#   owner: guests
#   system: examples
#   providesApis: [example-grpc-api]

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: merchants-API
spec:
  type: grpc
  lifecycle: staging
  owner: harikrishna.t.ravi
  system: Merchants
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: coupon-service
  description: A coupon service offers savings through vouchers
  annotations:
    github.com/project-slug: 'keycode-01/coupon-service'
spec:
  type: service
  lifecycle: production
  owner: lead
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: coupon-DB
  description: DB for coupon
spec:
  type: database
  lifecycle: production
  owner: dev
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: logistics-DB
  description: DB for logistics
spec:
  type: database
  lifecycle: production
  owner: lead
